
CREATE TABLE IF NOT EXISTS Environment(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  time TEXT NOT NULL,
  nodetype INTEGER NOT NULL,
  nodeid INTEGER NOT NULL,
  temperature FLOAT NOT NULL,
  humidity FLOAT NOT NULL,
  light FLOAT NOT NULL,
  CO2 FLOAT NOT NULL,
  nodein INTEGER NOT NULL,
  nodeout INTEGER NOT NULL,
  Cflag INTEGER NOT NULL,
  In485 TEXT NOT NULL
)